khm9990503/Kmarket1

Kmarket/member/css/member.css
Kmarket/member/join.html
Kmarket/member/login.html
Kmarket/member/register.html
Kmarket/member/registerSeller.html
Kmarket/member/signup.html

- 어제 작업 완료했던 login, join의 주소창(?)에 아이콘을 넣고 주소 이름을 '케이마켓::대한민국 1등 쇼핑몰'으로 수정하였습니다.
- css 중 common css 를 삭제하고 헤더, 푸터 공통을 member 폴더 안의 member.css로 모두 옮겼습니다.
- 오늘 login, join, signup, register, registerSeller 모두 작업(HTML) 완료 하였습니다.

2022/12/06 5개 모든 작업 완료하였습니다

---

Kmarket/admin/index.html
Kmarket/admin/list.html
Kmarket/css/admin.css
Kmarket/js/gnb.js

2022-12-16 화
1. css
- main/footer 작업완료(index) 
- 
2. js
- gnb.js 메뉴 슬라이드 구현완료

2022-12-06 css/js 작업

---

Kmarket/cs/css/CSstyle.css
Kmarket/cs/faq/list.html
Kmarket/cs/faq/view.html
Kmarket/cs/notice/view.html
Kmarket/cs/qna/list.html
Kmarket/cs/qna/view.html
Kmarket/cs/qna/write.html

2022/12/06 공지사항 cs, 자주묻는질문 faq, 문의하기qna 화면구현 완료 - 구홍모

2022/12/06 공지사항 완료, 자주묻는질문 작업중-구홍모

---

Kmarket/css/common.css
Kmarket/css/product.css
Kmarket/product/complete.html

- 상품 list, view, cart, order, complete 화면구현(HTML) 완료

2022/12/06 상품(Product) 화면구현 완료

---

Kmarket/member/css/member.css
Kmarket/member/join.html

- member 의 signup ' (선택)' 부분 css margin top >> margin right 로 수정했습니다,
- 다른 페이지 모두 검토했습니다.

2022/12/07 member의 signup css 수정

---

Kmarket/admin/index.html
Kmarket/admin/product/list.html
Kmarket/admin/product/register.html
Kmarket/css/admin.css

2022-12-07
1. 경로 수정
- html, css의 href/src 절대경로 > 상대경로로 수정 (/Kmarket1/Kmarket > ../../)

2022-12-07 href/src 경로 수정

---

Kmarket/member/css/member.css
Kmarket/member/findId.html
Kmarket/member/findIdResult.html
Kmarket/member/findPw.html
Kmarket/member/findPwResult.html

- findId, findPw, findIdResult, findPwResult 화면 4개 추가로 구현 했습니다.
- 제대로 열리는지 확인 부탁드려요.

findId, findPw, findIdResult, findPwResult 화면구현 완료

---

Kmarket/product/cart.html
Kmarket/product/complete.html
Kmarket/product/list.html
Kmarket/product/order.html
Kmarket/product/view.html

- product/*.html 일부 a 태그 # -> ./---.html 변경
- 카테고리.txt 참조하여 카테고리 변경

2022/12/08 a 태그 주소 일부 추가

---

Java1_Kmarket1/.classpath
Java1_Kmarket1/.settings/org.eclipse.wst.common.project.facet.core.xml
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/IndexController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/ListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/RegisterController.java
Java1_Kmarket1/src/main/webapp/admin/_footer.jsp
Java1_Kmarket1/src/main/webapp/admin/_header.jsp
Java1_Kmarket1/src/main/webapp/admin/index.jsp
Java1_Kmarket1/src/main/webapp/admin/product/list.jsp
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp

2022-12-08 목
controller 추가 및 img 경로수정

2022-12-08 Java1_Kmarket1 경로수정

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/IndexController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/ListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/RegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/Cate1VO.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/Cate2VO.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ProductVO.java
Java1_Kmarket1/src/main/webapp/admin/_header.jsp
Java1_Kmarket1/src/main/webapp/admin/index.jsp
Java1_Kmarket1/src/main/webapp/admin/product/list.jsp
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp

2022-12-09 admin vo 업데이트

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/member/SignupController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/MemberVO.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/PointVO.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/TermsVO.java
Java1_Kmarket1/src/main/webapp/member/_footer.jsp
Java1_Kmarket1/src/main/webapp/member/_header.jsp
Java1_Kmarket1/src/main/webapp/member/findId.jsp
Java1_Kmarket1/src/main/webapp/member/findIdResult.jsp
Java1_Kmarket1/src/main/webapp/member/findPw.jsp
Java1_Kmarket1/src/main/webapp/member/findPwResult.jsp
Java1_Kmarket1/src/main/webapp/member/join.jsp
Java1_Kmarket1/src/main/webapp/member/login.jsp
Java1_Kmarket1/src/main/webapp/member/register.jsp
Java1_Kmarket1/src/main/webapp/member/registerSeller.jsp
Java1_Kmarket1/src/main/webapp/member/signup.jsp

- memberVo, termsVo, PointVo 작업 완료 했습니다.
- member 각 페이지 이미지 절대 경로로 모두 변경했습니다.
- member a태그 주소 모두 '.do' 로 변경 했습니다.
- 컨트롤러에서 잘 열리는지 모두 확인 했습니다.

2022/12/09 vo 작업완료, member 각 페이지 절대경로 완료

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductRegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ArticleDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/CateDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/Cate2VO.java
Java1_Kmarket1/src/main/webapp/admin/_header.jsp
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp

2022/12/09 prod.register의 카테고리 리스트기능 작업-홍모

2022/12/09 prod.register의 카테고리 리스트기능 작업-홍모

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/member/RegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/member/SignupController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/MemberDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/TermsDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/DBHelper.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/member/join.jsp
Java1_Kmarket1/src/main/webapp/member/register.jsp
Java1_Kmarket1/src/main/webapp/member/signup.jsp

<join, signup>
- 개인구매(normal), 사업자판매(seller)  나누어서 이동
- 약관 db에서 불러오기 완료
- 동의 체크시 이동 완료

2022/12/09 terms 기능 구현 완료

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductRegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ProductVO.java
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp
Java1_Kmarket1/src/main/webapp/js/AdminProductRegister.js

register관련 작업
- ProductDao insertProduct 추가
- SQL INSERT_PRODUCT 추가
- AdminProductRegisterController 작업완료
- AdminProductRegister.js 작성중

2022-12-09 admin register 업데이트

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductRegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp
Java1_Kmarket1/src/main/webapp/js/AdminProductRegister.js

1. bizType 제거 (SQL, Dao, controller)
2. js 파일 주석처리

2022-12-09 admin bizType 제거 및 주석추가

---

Java1_Kmarket1/.classpath
Java1_Kmarket1/.settings/org.eclipse.jdt.core.prefs
Java1_Kmarket1/.settings/org.eclipse.wst.common.project.facet.core.xml
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductRegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ProductVO.java
Java1_Kmarket1/src/main/webapp/WEB-INF/web.xml
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp
Java1_Kmarket1/src/main/webapp/context.xml

2022/12/10 상품등록기능1차완료-구홍모

---

Java1_Kmarket1/src/main/webapp/css/member.css
Java1_Kmarket1/src/main/webapp/member/_header.jsp
Java1_Kmarket1/src/main/webapp/member/register.jsp

- 우편번호 버튼을 따로 생성하여 검색 후 (기본입력까지) 자동으로 입력되게 하였습니다.
- member.css을 수정 후 공통 css 폴더로 옮겼습니다.

2022/12/11 우편번호검색 기능 추가

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CartController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CompleteController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/OrderController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ViewController.java
Java1_Kmarket1/src/main/webapp/product/_header.jsp
Java1_Kmarket1/src/main/webapp/product/cart.jsp

- 카테고리 부분 product header에 추가(controller 추가)

2022/12/12 카테고리 부분 수정

---

Java1_Kmarket1/src/main/webapp/css/member.css
Java1_Kmarket1/src/main/webapp/js/validation.js
Java1_Kmarket1/src/main/webapp/member/register.jsp
Java1_Kmarket1/src/main/webapp/member/signup.jsp

signup 일부 수정

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/service/ProductService.java
Java1_Kmarket1/src/main/webapp/product/list.jsp

22/12/14 상품 기능 일부 시작

---

Java1_Kmarket1/src/main/webapp/css/main.css

2022/12/14 main thumb img 사이즈 조절-홍모

2022/12/14 main thumb img 사이즈 조절-홍모

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/IndexController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ArticleDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ArticleVO.java
Java1_Kmarket1/src/main/webapp/cs/index.jsp
Java1_Kmarket1/src/main/webapp/css/main.css
Java1_Kmarket1/src/main/webapp/index.jsp

2022/12/14 
- main 숫자 3자리마다 , 추가하는 기능완료 - 홍모
- cs index 리스트 구현 기능 완료.

2022/12/14 main 숫자 3자리마다 , 추가하는 기능완료 - 홍모

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/IndexController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/NoticeListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/NoticeViewController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ArticleDao.java
Java1_Kmarket1/src/main/webapp/cs/index.jsp
Java1_Kmarket1/src/main/webapp/cs/notice/list.jsp

2022/12/15 cs 공지사항 리스트 기능 구현 완료 - 홍모

2022/12/15 cs 공지사항 리스트 기능 구현 완료 - 홍모

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/service/ProductService.java
Java1_Kmarket1/src/main/webapp/css/product.css
Java1_Kmarket1/src/main/webapp/product/_header.jsp
Java1_Kmarket1/src/main/webapp/product/list.jsp

- 1차, 2차 카테고리 클릭으로 상품목록 출력
- 상품 10개까지 노출 후 페이징 처리 (유아동 - 출산/육아는 상품 12개로 2페이지까지 노출돼있음)

22/12/15 상품 목록 출력, 페이징 처리 완료

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/FaqListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/NoticeViewController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ArticleDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/service/ProductService.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ArticleVO.java
Java1_Kmarket1/src/main/webapp/cs/_header.jsp
Java1_Kmarket1/src/main/webapp/cs/faq/list.jsp
Java1_Kmarket1/src/main/webapp/cs/notice/view.jsp

2022/12/15 cs notice view 글보기 기능구현 완료

2022/12/15 cs notice view 글보기 기능구현 완료 

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/member/LogoutController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/member/RegisterController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/member/RegisterSellerController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/MemberDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/_header.jsp
Java1_Kmarket1/src/main/webapp/css/member.css
Java1_Kmarket1/src/main/webapp/js/validation2.js
Java1_Kmarket1/src/main/webapp/member/registerSeller.jsp
Java1_Kmarket1/src/main/webapp/member/signup.jsp

- main 로그인 했을 때 헤더 (로그아웃, 마이페이지), 로그아웃일 때 헤더 (로그인, 회원가입) 으로 변경하고 확인했습니다.
- registerSeller 최신 스토리보드에 매니저(담당자)가 없어서 제거하고 기능 구현했습니다.
- member 기능 다 구현되는지 확인 완료

2022/12/16 기능구현 완료 ,main header 변경 완료

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/NoticeListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductListDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/service/AdminProductService.java
Java1_Kmarket1/src/main/webapp/admin/_header.jsp
Java1_Kmarket1/src/main/webapp/admin/index.jsp
Java1_Kmarket1/src/main/webapp/admin/product/list.jsp
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022-12-16 금
1. admin/list
- register 등록상품 list 페이지 출력 완료
- page 구현
2. gnb
- gnb 텝 _header로 이동하여 통합

2022-12-16 list 상품출력

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ViewController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductRegisterDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/css/product.css
Java1_Kmarket1/src/main/webapp/product/list.jsp
Java1_Kmarket1/src/main/webapp/product/view.jsp

- list, view 페이징 네비게이션(home > ** > ** ) 완료

2022/12/18 상품 리스트, 뷰 기능

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductDeleteController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductModifyController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductListDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductRegisterDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ProductVO.java
Java1_Kmarket1/src/main/webapp/admin/product/list.jsp
Java1_Kmarket1/src/main/webapp/admin/product/modify.jsp

2022-12-19 월
1. list
- 수정 / 삭제 작업

2022-12-19 월

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSViewController.java
Java1_Kmarket1/src/main/webapp/admin/cs/list.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/view.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/write.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022/12/19 admin cs list view 기능구현 중 - 홍모

2022/12/19 admin cs list view 기능구현 중 - 홍모

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSModiController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSWriteController.java
Java1_Kmarket1/src/main/webapp/admin/cs/list.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/modify.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/view.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/write.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022/12/19 admin cs 수정 기능 구현 중

2022/12/19 admin cs 수정 기능 구현 중

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ViewController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/CartDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/CartVO.java
Java1_Kmarket1/src/main/webapp/product/view.jsp

- 리뷰 일부 수정 (select 문에 prodNo 지정)
- 총 상품금액(view), 장바구니(cart) 일부  코딩

2022/12/19 product 뷰 추가 작업

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductModifyController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductListDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductRegisterDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/admin/product/modify.jsp
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp

2022-12-20 화
admin list
상품 수정 get/post 구현 완료 (카테고리 수정 미구현)

2022-12-20 화

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSDeleteController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/cs/CSModiController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ArticleDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/CateDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/ArticleVO.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/Cate2VO.java
Java1_Kmarket1/src/main/webapp/admin/cs/list.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/view.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022/12/20 admin cs 글보기 답변 기능구현 중 - 홍모

2022/12/20 admin cs 글보기 답변 기능구현 중 - 홍모

---

Java1_Kmarket1/src/main/webapp/product/view.jsp

2022/12/20 product view 리뷰 아이디 마스킹 작업

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductListDao.java

2022-12-20 화
1. list
- 검색기능 작업시작

2022-12-20 list 검색기능

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CartController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/OrderController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/CartDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/css/product.css
Java1_Kmarket1/src/main/webapp/product/cart.jsp
Java1_Kmarket1/src/main/webapp/product/order.jsp

2022/12/21 product order 기능구현 중 - 홍모

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CartController.java
Java1_Kmarket1/src/main/webapp/product/cart.jsp

- sessUser 의 장바구니만 볼 수 있게 작업
- 체크박스 다중삭제, 전체합계 구현중

2022/12/21 product cart 작업

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/OrderController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/ViewController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/CartDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/OrderDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/OrderVO.java
Java1_Kmarket1/src/main/webapp/WEB-INF/web.xml
Java1_Kmarket1/src/main/webapp/css/product.css
Java1_Kmarket1/src/main/webapp/index.jsp
Java1_Kmarket1/src/main/webapp/index_.jsp
Java1_Kmarket1/src/main/webapp/product/_header.jsp
Java1_Kmarket1/src/main/webapp/product/complete.jsp
Java1_Kmarket1/src/main/webapp/product/order.jsp
Java1_Kmarket1/src/main/webapp/product/view.jsp

2022/12/22 product order 기능구현 완료

2022/12/22 product order 기능구현 완료

---

Java1_Kmarket1/src/main/webapp/admin/cs/list.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022/12/22 cs list 수정

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CartController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/CartDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/product/cart.jsp
Java1_Kmarket1/src/main/webapp/product/complete.jsp

2022/12/22 cart 작업 완료

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductListController.java
Java1_Kmarket1/src/main/webapp/admin/product/list.jsp
Java1_Kmarket1/src/main/webapp/admin/product/modify.jsp
Java1_Kmarket1/src/main/webapp/admin/product/register.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022-12-22 목
1. list
- 체크박스 전체 선택, 해제 기능 추가
- 개별체크 선택 및 해제 시 전체 체크 활성 및 비활성 기능 추가

2022-12-22 체크박스 기능 추가

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/OrderController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/OrderItemVO.java
Java1_Kmarket1/src/main/webapp/_header.jsp
Java1_Kmarket1/src/main/webapp/css/common.css
Java1_Kmarket1/src/main/webapp/product/_header.jsp
Java1_Kmarket1/src/main/webapp/product/complete.jsp
Java1_Kmarket1/src/main/webapp/product/order.jsp

2022/12/22 complete 상품부분 완료

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CartController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/CompleteController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/OrderController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/OrderDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/OrderItemDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/OrderItemVO.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/vo/OrderVO.java
Java1_Kmarket1/src/main/webapp/product/cart.jsp
Java1_Kmarket1/src/main/webapp/product/complete.jsp
Java1_Kmarket1/src/main/webapp/product/order.jsp

2022/12/22 complete 주문자 정보

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/product/OrderController.java
Java1_Kmarket1/src/main/webapp/product/order.jsp

2022/12/23 에러 수정

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductListController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductListDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/admin/_header.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/modify.jsp
Java1_Kmarket1/src/main/webapp/admin/cs/write.jsp
Java1_Kmarket1/src/main/webapp/admin/index.jsp
Java1_Kmarket1/src/main/webapp/cs/faq/list.jsp
Java1_Kmarket1/src/main/webapp/cs/qna/write.jsp
Java1_Kmarket1/src/main/webapp/product/view.jsp

2022/12/23 cs faq 더보기 간단히 보기 기능 보완 작업

2022/12/23 보완작업

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/controller/admin/product/AdminProductDeleteController.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/AdminProductListDao.java
Java1_Kmarket1/src/main/java/kr/co/kmarket1/db/SQL.java
Java1_Kmarket1/src/main/webapp/admin/product/list.jsp
Java1_Kmarket1/src/main/webapp/css/admin.css

2022-12-23 금
1. list
- 선택삭제 구현 완료

2022-12-23 금 끝!

---

Java1_Kmarket1/src/main/java/kr/co/kmarket1/dao/ProductDao.java
Java1_Kmarket1/src/main/webapp/index.jsp

2022/12/23 3차 수정

---

Java1_Kmarket1/src/main/webapp/admin/product/register.jsp
Java1_Kmarket1/src/main/webapp/cs/qna/list.jsp
Java1_Kmarket1/src/main/webapp/css/common.css
Java1_Kmarket1/src/main/webapp/css/main.css
Java1_Kmarket1/src/main/webapp/index.jsp

2022/12/27 추가작업 - 홍모
메인이랑 상품의 카테고리 2차 리스트의 CSS 통일
상품등록 시 500 에러 페이지를 막기 위해 유효성 등록 추가
문의하기 시  로그인 안하면 문의하기 작성 못하게 막음

2022/12/27 추가작업 - 홍모
